import express from "express";
import {checkAuth, login,logout,signup,updateProfile} from "../controllers/auth.controller.js";
import { checkAdminRoute, protectRoute } from "../middleware/auth.middleware.js";
import { createComment, createPost } from "../controllers/post.controller.js";
import { createProblem } from "../controllers/problem.controller.js";
import Problem from "../models/problem.model.js";
import Post from "../models/post.model.js";
const router=express.Router();
router.post("/signup",signup);
router.post("/login",login);
router.post("/logout",logout);
router.post("/update-profile",protectRoute,updateProfile);
router.get("/check", protectRoute, checkAuth);
export default router;
